fix: `ValueError` when running `fish_ai_switch_context`
The configuration file was loaded from the wrong location
causing the following error to occur when running
`fish_ai_switch_context`:

```
ValueError: list.remove(x): x not in list
```